package main

import "fmt"

func main() {

	var bigEvenSum int
	fibnumA := 0
	fibnumB := 1
	var fibnumC int

	//generate Fibonaccis

	for i := 1; i < 4000001; i++ {

		fibnumC = fibnumA + fibnumB
		fibnumA = fibnumB
		fibnumB = fibnumC

		fmt.Println("here is the next fibonacci number:", fibnumC)

		if fibnumC%2 == 0 {
			bigEvenSum = bigEvenSum + fibnumC
			fmt.Println("here is the current sum of even fibonaccis:", bigEvenSum)
		}
		if fibnumC >= 4000000 {
			break
		}

	}
	fmt.Println("* * * *")
	fmt.Println("here is the sum of even Fibonaccis under or equal to four million:", bigEvenSum)
}

/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/
